config/routes.rb
Rails.application.routes.draw do
  # resources :resumes, only: [:index, :new, :destroy]

  get 'syndicates/index'
  get 'syndicates/blog'
  get 'syndicates/about'
  get 'syndicates/contact'
  get 'syndicates/guard'
  get 'syndicates/service'
  get 'syndicates/careers'
  get 'syndicates/single'

  


  root 'sessions#new'


  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy'
  # post '/insert' , to: 'syndicates#new'
  post '/insert' , to: 'syndicates#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/resume.rb
class Resume < ApplicationRecord
    mount_uploader :res_attachment, ResAttachmentUploader # Tells rails to use this uploader for this model.
    validates :email, presence: true # Make sure the owner's name is present.
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :email, :presence => true, :uniqueness => true
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password,password_salt)
  end

  def self.authenticate(email, password)
    user = User.find_by "email = ?", email
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end


  def authorize
    if !current_user
      flash[:alert] = "You aren't authorized to visit that page."
      redirect_to '/'
    end
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end
 
  def new
    puts params[:first_name]
    puts resume_params
    @resume = Test.new(resume_params)
    
    if @resume.save
       redirect_to syndicates_careers_path, notice: "The resume #{@resume.first_name} has been uploaded."
    else
      puts @resume.errors.full_messages
       render syndicates_index_path
    end
  end
 
  def create
    puts resume_params,2222222222222222222222
    @resume = Resume.new(resume_params)
    
    if @resume.save
       redirect_to syndicates_careers_path, notice: "The resume #{@resume.first_name} has been uploaded."
    else
      puts @resume.errors.full_messages
       render syndicates_index_path
    end

  end
 
  def destroy
    @resume = Resume.find(params[:email])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.first_name} has been deleted."
  end

  private
  def resume_params
    puts "0000000000000000000000000000000000000000000000000"
    params.permit(:first_name)
    puts params[:first_name]
    puts 5555555555555555555555555555555555555555555555555555555555555555555
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'signin_layout'
  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to syndicates_index_path
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/syndicates_controller.rb
class SyndicatesController < ApplicationController

  

  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    puts params[:first_name]
    puts resume_params
    @resume = Resume.new(resume_params)
    
    if @resume.save
       redirect_to syndicates_index_path, notice: "The resume #{@resume.first_name} has been uploaded."
    else
      puts @resume.errors.full_messages
       render syndicates_index_path
    end
  end

  def about
  end

  def contact
  end

  def guard
  end

  def service
  end

  def single
  end

  def careers
    @resumes = Resume.all
  end

  private
  def resume_params
    params.permit(:first_name,:last_name,:dob,:marital_status,:gender,:mob_num,:email,:current_address,:experience,:key_skills,:res_attachment)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'signup_layout'
	def new
		@user = User.new
	
		# render layout: 'syndicate_layout'
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You've successfully signed up!"
			session[:user_id] = @user.id
			redirect_to "/"
		else
			flash[:alert] = "There was a problem signing up."
			redirect_to '/signup'
		end
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/syndicates_helper.rb
module SyndicatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheSyndicate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= yield %>

    <% if current_user %>
      <div class="flash-notice" style="display: inline-block;">
        <%= flash[:notice] %>
      </div>
      <%= current_user.email %> | <%= link_to "Sign out", '/signout' %>
    <% end %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.6/dist/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

  </body>
</html>

app/views/layouts/signin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="login-page">
    <h1 class="main-title">TheSyndicate</h1>
    <!-- <div class="d-flex justify-content-center"> -->
      <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="d-flex justify-content-center">
               <main>
                 <%= yield %>
               </main>
            </div>
        </div>
      </div>
    <!-- </div> -->

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

app/views/layouts/signup_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DonX</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="login-page">
    <h1 class="main-title">TheSyndicate</h1>
    <!-- <div class="d-flex justify-content-center"> -->
      <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <div class="d-flex justify-content-center">
               <main>
                 <%= yield %>
               </main>
            </div>
        </div>
      </div>
    <!-- </div> -->

  </body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<h1>Resumes#index</h1>
<p>Find me in app/views/resumes/index.html.erb</p>

app/views/resumes/new.html.erb
<h1>Resumes#new</h1>
<p>Find me in app/views/resumes/new.html.erb</p>

app/views/syndicates/careers.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>SafetyFirst - Security Guard Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free Website Template" name="keywords">
    <meta content="Free Website Template" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Flaticon Font -->
    <link href="lib/flaticon/font/flaticon.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body class="bg-white">
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-lg-5">
            <div class="col-lg-6 text-center text-lg-left">
                <div class="d-inline-flex align-items-center">
                    <p class="mr-2 mb-2 mb-lg-0 text-white">Opening Hours:</p>
                    <span class="mb-2 mb-lg-0 text-white">8.00AM - 9.00PM</span>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <p class="m-0 mr-1 text-white">Follow Us:</p>
                    <a class="text-white px-2" href="https://www.facebook.com/">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-2" href="https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoiZW4ifQ%3D%3D%22%7D">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-2" href="https://in.linkedin.com/">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-2" href="https://www.instagram.com/">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white px-2" href="https://www.youtube.com/">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row py-3 px-lg-5">
            <div class="col-lg-4">
                <a href="" class="navbar-brand d-none d-lg-block">
                    <h1 class="m-0 display-5 text-capitalize font-italic"><span class="text-primary">The</span>Syndicate</h1>
                </a>
            </div>
            <div class="col-lg-8 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <div class="d-inline-flex flex-column text-center pr-3 border-right">
                        <h6>Our Lair</h6>
                        <p class="m-0">666-Street,Chotta-Nagar,Navi-Mumbai</p>
                    </div>
                    <div class="d-inline-flex flex-column text-center px-3 border-right">
                        <h6>Email Us</h6>
                        <p class="m-0">donsharique@outlook.com</p>
                    </div>
                    <div class="d-inline-flex flex-column text-center pl-3">
                        <h6>Call Us</h6>
                        <p class="m-0">+919072722024</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0 mb-5">
        <nav class="navbar navbar-expand-lg bg-secondary navbar-dark py-0">
            <a href="" class="navbar-brand d-block d-lg-none">
                <h1 class="m-0 display-5 text-capitalize font-italic text-white"><span class="text-primary">Safety</span>First</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav m-auto py-4">
                    <%= link_to "Home", syndicates_index_path, class: 'nav-item nav-link' %>
                    <%= link_to "About",syndicates_about_path,class: 'nav-item nav-link' %>
                    <%= link_to "Services",syndicates_service_path,class: 'nav-item nav-link' %>
                    <%= link_to "Guards", syndicates_guard_path, class:'nav-item nav-link' %>
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                    <li class="nav-item dropdown">
                                       <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Pages</a>
                                            <ul class="dropdown-menu">
                                                <%# <li><a class="dropdown-item" href="#">Action</a></li> %>
                                                <%= link_to "Blog Grid",syndicates_blog_path,class: 'dropdown-item' %>
                                                <li><hr class="dropdown-divider"></li>
                                                <%= link_to "Blog Details",syndicates_single_path,class: 'dropdown-item' %>
                                            </ul>
                                    </li>
                                </ul>
                            </div>
                    <%= link_to "Contact",syndicates_contact_path,class: 'nav-item nav-link' %>
                    <%= link_to "Careers",syndicates_careers_path,class: 'nav-item nav-link active' %>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->


    <!-- Contact Start -->
    
        <div class="d-flex flex-column text-center mb-5">
            <h5 class="text-primary mb-3">Join Us</h5>
            <h1 class="m-0">Build Your Career With Us</h1>
                <!-- <form action="/insert" method="POST"> -->
                    <%= form_with model: @resume, url: insert_path,html: { multipart: true }, method: :post do |form| %><br>

                        <%= form.text_field :first_name, placeholder: "First Name" %>&emsp;&trade;&reg;&copy;

                        <%= form.text_field :last_name, placeholder: "Last Name" %><br><br>

                        <%= form.text_field :dob, placeholder: "DOB" %>&emsp;

                        <%= form.text_field :marital_status, placeholder: "Marital Status" %><br><br>

                        <%= form.text_field :gender, placeholder: "Gender" %>&emsp;

                        <%= form.text_field :mob_num, placeholder: "Mobile Number" %><br><br>

                        <%= form.text_field :email, placeholder: "Email" %>&emsp;

                        <%= form.text_field :current_address, placeholder: "Current Address" %><br><br>

                        <%= form.text_field :experience, placeholder: "Experience" %>&emsp;

                        <%= form.text_field :key_skills, placeholder: "Key Skills" %><br><br>

                        <%= form.file_field :res_attachment %><br><br>

                        <%= form.submit "Submit", class: "btn btn-primary" %>

                    <% end %>


      
        </div>



    <!-- Contact End -->


    <!-- Footer Start -->
    <div class="container-fluid bg-success text-white mt-5 py-5 px-sm-3 px-md-5">
        <div class="row pt-5">
            <div class="col-lg-4 col-md-12 mb-5"><br><br><br>
                <h1 class="m-0 display-5 text-capitalize font-italic text-white"><span class="text-primary">The</span>Syndicate</h1>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="text-primary mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Team</a>
                            <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-primary mb-4">Popular Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>About Us</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Services</a>
                            <a class="text-white mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Our Team</a>
                            <a class="text-white" href="#"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="text-primary mb-4">Get In Touch</h5>
                        <p><i class="fa fa-map-marker-alt mr-2"></i>123 Street, New York, USA</p>
                        <p><i class="fa fa-phone-alt mr-2"></i>+012 345 67890</p>
                        <p><i class="fa fa-envelope mr-2"></i>infoo@example.com</p>
                        <div class="d-flex justify-content-start mt-4">
                            <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 40px; height: 40px;" href="#"><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 40px; height: 40px;" href="#"><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 40px; height: 40px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                            <a class="btn btn-outline-light rounded-circle text-center mr-2 px-0" style="width: 40px; height: 40px;" href="#"><i class="fab fa-instagram"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row pt-3">
            <div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
                <p class="m-0 text-white">
                    &copy; <a class="text-white font-weight-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed by
                    <a class="text-white font-weight-bold" href="https://htmlcodex.com">HTML Codex</a>
                </p>
            </div>
            <div class="col-md-6 text-center text-md-right">
                <ul class="nav d-inline-flex">
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Terms</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">FAQs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-white py-0" href="#">Help</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-secondary border back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

app/views/users/new.html.erb
<h1 class="sign_up"> Sign up</h1>
<%= form_for @user do |f| %>

<div class = "form-group form-control-sm">
  <%= f.label "Email", class: 'custom-font' %>&nbsp;&emsp;&nbsp;&nbsp;
  <%= f.text_field :email %><br>
</div>

<div class = "form-group form-control-sm">
  <%= f.label "Password", class: 'custom-font' %>
  <%= f.password_field :password %><br>
</div>

<div class = "form-group form-control-sm">
  <%= f.label :password_confirmation, class: 'custom-font' %>
  <%= f.password_field :password_confirmation %><br>
</div>

<div class="actions">
  <%= f.submit "Sign up", class:'btn btn-secondary' %>
  <%= link_to "Sign in?", signin_path , class:'btn btn-primary' %>
</div>

<% end %>